package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"fmt"
	"ozonTech/graph/model"
	"ozonTech/internal/models"
	"ozonTech/internal/pkg/middleware"
	"strconv"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, title string, content string, commentsAllowed bool) (*model.Post, error) {
	id, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("id user not found")
	}
	return r.PostUsecase.CreatePost(&models.PostCreateData{
		Title:           title,
		Content:         content,
		CommentsAllowed: commentsAllowed,
		UserID:          id,
	})
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, postID string, parentID *string, content string) (*model.Comment, error) {
	intPostID, err := strconv.ParseInt(postID, 10, 64)
	if err != nil {
		return nil, errors.New("invalid post id")
	}
	var intParentCommentID int64
	if parentID != nil {
		intParentCommentID, err = strconv.ParseInt(*parentID, 10, 64)
		if err != nil {
			return nil, errors.New("invalid parent comment id")
		}
	}
	id, ok := middleware.GetUserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("id user not found")
	}
	return r.CommentUsecase.CreateComment(&models.CommentCreateData{
		PostID:          int(intPostID),
		ParentCommentID: int(intParentCommentID),
		Text:            content,
		UserID:          id,
	})
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, name string, password string) (string, error) {
	token, err := r.AuthUsecase.SignUp(name, password)
	if err != nil {
		return "", err
	}
	return token, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, name string, password string) (string, error) {
	token, err := r.AuthUsecase.Login(name, password)
	if err != nil {
		return "", err
	}
	return token, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	posts, err := r.PostUsecase.GetAllPosts()
	if err != nil {
		return nil, err
	}

	var gqlPosts []*model.Post
	for _, post := range posts {
		gqlPosts = append(gqlPosts, post)
	}

	return gqlPosts, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	intID, err := strconv.Atoi(id)
	if err != nil {
		return nil, fmt.Errorf("invalid post ID")
	}

	return r.PostUsecase.GetPostByID(intID)
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentAdded - commentAdded"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
