// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string     `json:"id"`
	PostID          string     `json:"postID"`
	UserID          string     `json:"userID"`
	ParentCommentID *string    `json:"parentCommentID,omitempty"`
	ChildComments   []*Comment `json:"childComments,omitempty"`
	Content         string     `json:"content"`
}

type Mutation struct {
}

type Post struct {
	ID              string     `json:"id"`
	UserID          string     `json:"userID"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CommentsAllowed bool       `json:"commentsAllowed"`
	Comments        []*Comment `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
